[package]
name = "local_list"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9"
sha2 = "0.9"
walkdir = "2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
