# fish
# git add ../.github;git commit --amend --no-edit ;git push --force

name: release-binaries
# on:
#   release:
#     types: [published]
on:
  push

jobs:
  windows-x86_64:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./local_list
    steps:
      - uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path ./local_list/Cargo.toml
          # use-cross: true
      
      # - name: Release
      #   uses: eine/tip@master
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     files: target/release/local_list.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: local_list/target/release/local_list.exe
          tag_name: tip
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     draft: false
      #     prerelease: false
      # - name: Upload binary
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     asset_name: local_list-windows-x86_64.exe
      #     asset_path: target/release/local_list.exe
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_content_type: application/octet-stream
      #     tag_name: tip
